
language: php
php:
  - '7.0'

before_script:
#  - sudo apt-get update && sudo apt-get install -my software-properties-common && sudo add-apt-repository -y ppa:ondrej/php
  - sudo apt-get update
#  - sudo apt-get install php-mongodb
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer update
#  - make deps

after_script:
  - php vendor/bin/coveralls -v

notifications:
  email:
    - jose.gilmolina@gmail.com

