language: php

php:
  - 7.0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

services:
  - mongodb

before_install:
    - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
    - composer install

after_script:
  - php vendor/bin/coveralls
  - php vendor/bin/coveralls -v

notifications:
  email:
    - jose.gilmolina@gmail.com

